pipelines:
  - name: check
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: comment-added
          branch: master
          comment_filter: (?i)^\s*recheck migrations\s*$
        - event: comment-added
          branch: master
          comment_filter: (?i)^\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$
        - event: comment-added
          branch: master
          approval:
            - verified: 1
          email_filter: ^this_will_not_trigger_for_now$
        - event: patchset-created
          branch: master
        - event: change-restored
          branch: master
    start:
      smtp:
        to: "joshua.hesketh+zuul-test@gmail.com, matt+zuul-test@oliver.net.au"
    success:
      smtp:
#        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
        to: "joshua.hesketh+zuul-test@gmail.com, matt+zuul-test@oliver.net.au"
#      gerrit:
#        verified: 1
#      mysql:
#        verified: 1
    failure:
      smtp:
        to: "joshua.hesketh+zuul-test@gmail.com, matt+zuul-test@oliver.net.au"
#        to: "joshua.hesketh@gmail.com, rcbau@lists.rcbops.com"
#      mysql:
#        verified: -1
#      gerrit:
#        verified: -1
    success-message: "Database migration testing successful."
    failure-message: "Database migration testing failed either due to migrations unable to be applied correctly or taking too long."

  - name: experimental
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          comment_filter: (?i)^\s*check experimental migrations\s*$
    start:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    success:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    failure:
      smtp:
        to: "joshua.hesketh@gmail.com, michael.still@rackspace.com"
    success-message: "Experimental database migration testing successful."
    failure-message: "Experimental database migration testing failed either due to migrations unable to be applied correctly or taking too long."

  - name: silent
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          branch: master
          comment_filter: (?i)^\s*this silent thing should never trigger\s*$
    start:
      smtp:
        to: "michael.still@rackspace.com"
    success:
      smtp:
        to: "michael.still@rackspace.com"
    failure:
      smtp:
        to: "michael.still@rackspace.com"
    success-message: "Silent test passed"
    failure-message: "Silent test failed"

jobs:
  - name: ^real-db-upgrade_.*$
    failure-message: Database updates did not apply well to a real set of data...
  - name: ^thw[0-9]+_-real-db-upgrade_.*$
    failure-message: Experimental checks did not complete...
  - name: ^.*user_001$
    voting: true

projects:
  - name: openstack/nova
    check:
      - real-db-upgrade_nova_mysql_devstack_131007
      - real-db-upgrade_nova_mysql_user_001
      - real-db-upgrade_nova_percona_devstack_131007
      - real-db-upgrade_nova_percona_user_001
      - real-db-upgrade_nova_mysql_user_002
      - real-db-upgrade_nova_percona_user_002
    experimental:
      - thw-mysql-010_real-db-upgrade_nova_mysql_user_001
      - thw-percona-010_real-db-upgrade_nova_percona_user_001
    silent:
      - real-db-upgrade_nova_mysql_devstack_131007
      - real-db-upgrade_nova_mysql_user_001
      - real-db-upgrade_nova_percona_devstack_131007
      - real-db-upgrade_nova_percona_user_001
      - real-db-upgrade_nova_mysql_user_002
      - real-db-upgrade_nova_percona_user_002

